### ISSUE TITLE
`{"message":"Not Found","documentation_url":"https://docs.github.com/rest"} (404)`

### ISSUE THREAD

**Issue by nilsreichardt** [nilsreichardt/codemagic-app-preview#54]
```
Exception: Failed to get comments: {"message":"Not Found","documentation_url":"https://docs.github.com/rest"} (404)
#0      GitHubApiRepository.getComments (package:codemagic_app_preview/src/github/github_api_repository.dart:87:7)
<asynchronous suspension>
#1      CommentPoster.post (package:codemagic_app_preview/src/comment/comment_poster.dart:16:22)
<asynchronous suspension>
#2      PostCommand.run (package:codemagic_app_preview/src/commands/post_command.dart:66:5)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
```

**Comment by nilsreichardt** [comment]
Can're reproduce it...
